name: ESLint Check

on:
    pull_request:
        branches:
            - main

jobs:
    eslint:
        runs-on: ubuntu-latest

        steps:
            - name: check out repo
              uses: actions/checkout@v4

            - name: set up node
              uses: actions/setup-node@v4
              with:
                  node-version: 18

            - name: npm install
              run: npm ci

            - name: eslint
              run: npm run lint